---
galaxy_info:
  role_name: excel_generator
  author: OSO
  description: Generate Excel reports from Kafka performance test results
  company: OSO DevOps
  license: Apache-2.0
  min_ansible_version: "2.15"
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
        - noble
    - name: EL
      versions:
        - "8"
        - "9"
    - name: Debian
      versions:
        - bullseye
        - bookworm
  galaxy_tags:
    - kafka
    - performance
    - testing
    - excel
    - reporting

dependencies:
  - role: log_parser
    when: latest_parsed_file is not defined
