---

- name: Process variables
  hosts: all
  gather_facts: false
  tags: test
  tasks:
    - name: Gather OS Facts
      setup:
        gather_subset:
          - '!all'
          - '!any'
          - user
          - os_family
          - hardware
      tags: always

- name: Execute performance test
  hosts: all
  gather_facts: false
  become: true
  tags: test, performance
  vars:
    perf_topic_name: platform-test
    perf_parallel: true
    perf_report_file: scenario1_p1_c3.log
    perf_topic_partitions: 36
    perf_replication_factor: 3
    perf_linger_ms: 10
    perf_buffer_memory: 67108864
    perf_throughput: -1
    perf_record_size: 1024
    perf_num_records: 10000000
    perf_batch_size: 128000

    # Remote hosts to run the performance tests on.
    perf_hosts:
      kafka-broker-1.dev: # Amended to match the broker host in the test environment
        producers: 1
        consumers: 1
        c_groups: ['perf-test-1']
      kafka-broker-2.dev:  # Amended to match the broker host in the test environment
        consumers: 1
        c_groups: ['perf-test-2']
      kafka-broker-3.dev: # Amended to match the broker host in the test environment
        consumers: 1
        c_groups: ['perf-test-3']
  tasks:
    - import_role:
        name: tests
        tasks_from: performance.yml
