---
galaxy_info:
  role_name: cleanup
  author: OSO
  description: Cleanup after Kafka performance testing
  company: OSO DevOps
  license: Apache-2.0
  min_ansible_version: "2.15"
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
        - noble
    - name: EL
      versions:
        - "8"
        - "9"
    - name: Debian
      versions:
        - bullseye
        - bookworm
  galaxy_tags:
    - kafka
    - performance
    - testing
    - cleanup

dependencies: []
